### ISSUE TITLE
Run sample gltf viewer

### ISSUE THREAD

**Issue by luung1704** [minhchiihg/SE04-Nhom13.1#3]
- Sample đang bị lỗi không run được

![image](https://user-images.githubusercontent.com/71346057/103303964-f3466400-4a39-11eb-93b4-c247e202c22a.png)

**Comment by luung1704** [comment]
![image](https://user-images.githubusercontent.com/71346057/103303933-d90c8600-4a39-11eb-8c19-59a37ca0a1a1.png)
bị lỗi không run được sample

**Comment by luung1704** [comment]
Sample chưa chạy được do Filament phải build trước khi chạy
https://github.com/google/filament/blob/main/android/Windows.md

**Comment by luung1704** [comment]
gặp lỗi Detected C compiler MINGW  and MINGW is unsupported

**Comment by luung1704** [comment]
- gặp lỗi file is not able to compile a simple test program 
- đã sửa:  
+ thêm SET (CMAKE_C_COMPILER_WORKS 1) và SET (CMAKE_CXX_COMPILER_WORKS 1) vào file CMakeList.txt trong thư mục filament

**Comment by luung1704** [comment]
- Error: Building with Clang on Windows is no longer supported.  Use MSVC 2019
- Đã sửa: sau khi check thì thấy đã dùng VS 2019 rồi nhưng vẫn bị lỗi, có thể do quá trình kiểm tra bị nhầm, xóa dòng 216 đến dòng 220 trong file CMakeList.txt là chạy được

**Comment by minhchiihg** [comment]
Error SDK location not found
Đã sửa
![image](https://user-images.githubusercontent.com/63506928/103330392-e5253180-4a93-11eb-990f-65d147cdd835.png)

**Comment by luung1704** [comment]
✅ Done
![image](https://user-images.githubusercontent.com/71346057/103345458-09990200-4ac4-11eb-843c-2fd8330c742c.png)

**Comment by luung1704** [comment]
- Lỗi
https://user-images.githubusercontent.com/71346057/103389791-9b941f80-4b43-11eb-848b-08967e73017c.png

**Comment by luung1704** [comment]
- Build & run thành công, close issue

![image](https://user-images.githubusercontent.com/71346057/103464203-6adf0080-4d64-11eb-86c8-83d94b63c2f1.png)
