### ISSUE TITLE
Lỗi

### ISSUE THREAD

**Issue by luung1704** [minhchiihg/SE04-Nhom13.1#7]
![103389791-9b941f80-4b43-11eb-848b-08967e73017c](https://user-images.githubusercontent.com/71346057/103406414-36fdb280-4b8d-11eb-9a8f-4c35078e10ec.png)

**Comment by luung1704** [comment]
- build lại nhiều lần nhưng vẫn không được

**Comment by luung1704** [comment]
- Cài lại java, cài lại VS2019, cài lại python cmake ninja,.... vẫn không được

**Comment by minhchiihg** [comment]
![image](https://user-images.githubusercontent.com/63506928/103412952-2e67a500-4baa-11eb-8025-bd77704c63d1.png)

- Gặp lỗi cmake, đã đổi trình dịch sang clang, cài lại nhma vẫn không được

**Comment by minhchiihg** [comment]
![image](https://user-images.githubusercontent.com/63506928/103413301-8652db80-4bab-11eb-881a-d2e188188aa3.png)

- Cũng đang gặp lỗi cmake, huhu ..

**Comment by luung1704** [comment]
> ![image](https://user-images.githubusercontent.com/63506928/103413301-8652db80-4bab-11eb-881a-d2e188188aa3.png)
> 
> * Cũng đang gặp lỗi cmake, huhu 

chuyển sang dùng clang là được

**Comment by luung1704** [comment]
Do lỗi chưa gài git for Windows 
sau khi cài git for Windows vẫn bị lỗi

**Comment by luung1704** [comment]
đã sửa: vì Command Prompt của VS2019 không mở được file bash .sh, nên bị thiếu file libfilamat_combine.a và nhiều file khác vì thế nên phải chạy Git Bash và chạy các file bash bằng tay để out ra đủ các file rồi chạy lại ninja install
